import org.junit.Assert;
import org.junit.Test;
import ru.ifmo.cs.korm.annotations.Attribute;
import ru.ifmo.cs.korm.annotations.Table;

import java.sql.SQLException;

public class TestAdd {

    @Test
    public void testGeneratedAdd() throws SQLException {
        B b = new B();
        b.setA1(-1);
        b.setA2(12);
        B[] bs2 = {b};
        Utils.getNewSession().addClass(B.class).add(bs2);
        Assert.assertEquals(12, bs2[0].getA2());
        Assert.assertNotEquals(-1, bs2[0].getA1());
    }

    @Table(name = "b")
    public class B {
        @Attribute(name = "a1", autoGenerated = true)
        long a1;
        @Attribute(name = "a2")
        long a2;

        public long getA1() {
            return a1;
        }

        public void setA1(long a1) {
            this.a1 = a1;
        }

        public long getA2() {
            return a2;
        }

        public void setA2(long a2) {
            this.a2 = a2;
        }
    }

}
